<?php defined('SYSPATH') OR die('No direct access allowed.');
/**
 * @package  Timeline
 *
 * Default paths to scan for tests.
 */
$config['face']['风扇']='fan.gif';
$config['face']['冰棍']='ice.gif';
$config['face']['西瓜']='watermelon.gif';
$config['face']['照相机']='camera_thumb.gif';
$config['face']['自行车']='zxc_thumb.gif';
$config['face']['织']='zz2_thumb.gif';
$config['face']['围观']='wg_thumb.gif';
$config['face']['威武']='vw_thumb.gif';
$config['face']['给力']='geili_thumb.gif';
$config['face']['神马']='horse2_thumb.gif';
$config['face']['浮云']='fuyun_thumb.gif';
$config['face']['奥特曼']='otm_thumb.gif';
$config['face']['兔子']='rabbit_thumb.gif';
$config['face']['网球']='wangqiu_thumb.gif';
$config['face']['实习']='sx_thumb.gif';

$config['face']['呵呵']='smile.gif';
$config['face']['嘻嘻']='tooth.gif';
$config['face']['哈哈']='laugh.gif';
$config['face']['爱你']='love.gif';
$config['face']['晕']='dizzy.gif';
$config['face']['泪']='sad.gif';
$config['face']['馋嘴']='cz_thumb.gif';
$config['face']['抓狂']='crazy.gif';
$config['face']['哼']='hate.gif';
$config['face']['抱抱']='bb_thumb.gif';
$config['face']['可爱']='tz_thumb.gif';
$config['face']['怒']='angry.gif';
$config['face']['汗']='sweat.gif';
$config['face']['困']='sleepy.gif';
$config['face']['害羞']='shame_thumb.gif';
$config['face']['睡觉']='sleep_thumb.gif';
$config['face']['钱']='money_thumb.gif';
$config['face']['偷笑']='hei_thumb.gif';
$config['face']['酷']='cool_thumb.gif';
$config['face']['衰']='cry.gif';
$config['face']['吃惊']='cj_thumb.gif';
$config['face']['闭嘴']='bz_thumb.gif';
$config['face']['鄙视']='bs2_thumb.gif';
$config['face']['挖鼻屎']='kbs_thumb.gif';
$config['face']['花心']='hs_thumb.gif';
$config['face']['鼓掌']='gz_thumb.gif';
$config['face']['失望']='sw_thumb.gif';
$config['face']['思考']='sk_thumb.gif';
$config['face']['生病']='sb_thumb.gif';
$config['face']['亲亲']='qq_thumb.gif';
$config['face']['怒骂']='nm_thumb.gif';
$config['face']['太开心']='mb_thumb.gif';
$config['face']['懒得理你']='ldln_thumb.gif';

$config['face']['右哼哼']='yhh_thumb.gif';
$config['face']['左哼哼']='zhh_thumb.gif';
$config['face']['嘘']='x_thumb.gif';
$config['face']['委屈']='wq_thumb.gif';
$config['face']['吐']='t_thumb.gif';
$config['face']['可怜']='kl_thumb.gif';
$config['face']['打哈气']='k_thumb.gif';
$config['face']['顶']='d_thumb.gif';
 
$config['face']['疑问']='yw_thumb.gif';
$config['face']['做鬼脸']='zgl_thumb.gif';
$config['face']['握手']='ws_thumb.gif';
$config['face']['耶']='ye_thumb.gif';
$config['face']['good']='good_thumb.gif';
$config['face']['弱']='sad_thumb.gif';
$config['face']['不要']='no_thumb.gif';
$config['face']['ok']='ok_thumb.gif';
$config['face']['赞']='z2_thumb.gif';
$config['face']['来']='come_thumb.gif';
$config['face']['蛋糕']='cake.gif';
$config['face']['心']='heart.gif';
$config['face']['伤心']='unheart.gif';
$config['face']['钟']='clock_thumb.gif';
$config['face']['猪头']='pig.gif';
$config['face']['话筒']='m_thumb.gif';
$config['face']['月亮']='moon.gif';
$config['face']['太阳']='sun.gif';
$config['face']['下雨']='rain.gif';

